use_frameworks!

target 'DialCountries_Example' do
  pod 'DialCountries', :path => '../'

  target 'DialCountries_Tests' do
    inherit! :search_paths

   # pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
